<?php

/**
 * Implements hook_context_registry().
 */
function manidora_context_context_registry() {
  return array(
    'reactions' => array(
      'manidora_context_reaction_alter_music' => array(
        'title' => t('Alter objects for Faculty of Music'),
        'description' => t("Alter the object display to use special Faculty of Music display."),
        'plugin' => 'manidora_context_reaction_alter_music',
      ),
      'manidora_context_reaction_display_download' => array(
        'title' => t('Disable the Download tab'),
        'description' => t('For the matching objects do not display the Download tab, does NOT restrict direct access'),
        'plugin' => 'manidora_context_reaction_display_download',
      ),
    ),
  );
}

/**
 * Implements hook_context_plugins().
 */
function manidora_context_context_plugins() {
  return array(
    'manidora_context_reaction_alter_music' => array(
      'handler' => array(
        'path' => drupal_get_path('module', 'manidora_context') . '/plugins',
        'file' => 'manidora_context_reaction_music_compound.inc',
        'class' => 'ManidoraContextReactionMusicCompound',
        'parent' => 'context_reaction',
      ),
    ),
    'manidora_context_reaction_display_download' => array(
      'handler' => array(
        'path' => drupal_get_path('module', 'manidora_context') . '/plugins',
        'file' => 'manidora_context_reaction_disable_download.inc',
        'class' => 'ManidoraContextReactionDisableDownload',
        'parent' => 'context_reaction',
      ),
    ),
  );
}

function manidora_context_islandora_compoundcmodel_islandora_view_object_alter(AbstractObject $object, &$rendered) {
  if ($plugin = context_get_plugin('reaction', 'manidora_context_reaction_alter_music')) {
    if ($markup = $plugin->execute($object)) {
      if (isset($rendered[NULL])) {
        $rendered[NULL]['#markup'] = drupal_render($markup);
      }
    }
  }
}

function manidora_context_manidora_download_access(AbstractObject $object) {
  if ($plugin = context_get_plugin('reaction', 'manidora_context_reaction_display_download')) {
    return $plugin->execute();
  }
  return NULL;
}

/**
 * Implements hook_manidora_detail_view().
 */
function manidora_context_manidora_detail_view(AbstractObject $object) {
  islandora_context_islandora_view_object($object);
}

/**
 * Implements hook_manidora_download_view().
 */
function manidora_context_manidora_download_view(AbstractObject $object) {
  islandora_context_islandora_view_object($object);
}
